name: Update Jimin iTunes

on:
  schedule:
    # tiap 1 jam
    - cron: "0 * * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browser
        run: npx playwright install chromium

      - name: Run scraper
        run: node jimin-itunes.js

      - name: Commit updated JSON
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add data/jimin-itunes.json

          git diff --cached --quiet || git commit -m "auto update iTunes data"

          git push
